name: Java CI

on:
  push:
    branches:
      - '**/main'
      - '**/dev'
  workflow_dispatch:
    inputs:
      norelease:
        description: 'Do not publish'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v2
        with:
          fetch-depth: 30 # Gets the last 30 commits so the changelog might work
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        id: build
        env:
          SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs\/heads\/(\d|\.)+\/main$ ]]; then
              echo ::set-output name=release::true
          fi
          chmod +x ./gradlew
          ./gradlew build publish --stacktrace --no-daemon
      - name: Release to CurseForge
        if: |
          steps.build.outputs.release == 'true' && endsWith(github.ref, '/main') && !contains(github.event.head_commit.message, '[norelease]') && github.event.inputs.norelease != 'true'
        env:
          GIT_COMMIT: ${{ github.event.after }}
          GIT_PREVIOUS_COMMIT: ${{ github.event.before }}
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
        run: |
          chmod +x ./gradlew
          ./gradlew build curseforgePublish --stacktrace --no-daemon